# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/user/final_7/final_7.cache/wt [current_project]
set_property parent.project_path C:/Users/user/final_7/final_7.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{c:/Users/OneDrive - 清華大學/桌面/final_thing/ip}} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/user/final_7/final_7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/king_all.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/map.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/end_title.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/init_title.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/end_title_2.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/init_title_2.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/title_logo.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/crown.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/space.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/space_2.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/map_with_crown.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/crown_2.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/restart.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/restart_2.coe
add_files C:/Users/user/final_7/final_7.srcs/sources_1/imports/Pictrans/king_all_2.coe
read_verilog -library xil_defaultlib {
  C:/Users/user/final_7/final_7.srcs/sources_1/new/clock_divider.v
  C:/Users/user/final_7/final_7.srcs/sources_1/new/keyboard_decoder.v
  C:/Users/user/final_7/final_7.srcs/sources_1/new/mem_addr_gen.v
  C:/Users/user/final_7/final_7.srcs/sources_1/imports/lab8_template/music_example.v
  C:/Users/user/final_7/final_7.srcs/sources_1/imports/lab8_template/note_gen.v
  C:/Users/user/final_7/final_7.srcs/sources_1/new/onepulse.v
  C:/Users/user/final_7/final_7.srcs/sources_1/imports/lab8_template/player_control.v
  C:/Users/user/final_7/final_7.srcs/sources_1/imports/lab8_template/speaker_control.v
  C:/Users/user/final_7/final_7.srcs/sources_1/new/vga.v
  C:/Users/user/final_7/final_7.srcs/sources_1/new/top.v
}
read_ip -quiet C:/Users/user/final_7/final_7.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.xci

read_ip -quiet C:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet C:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all c:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet C:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property used_in_implementation false [get_files -all c:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3_ooc.xdc]

read_ip -quiet C:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all c:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]

read_ip -quiet C:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.xci
set_property used_in_implementation false [get_files -all c:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5_ooc.xdc]

read_ip -quiet C:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6.xci
set_property used_in_implementation false [get_files -all c:/Users/user/final_7/final_7.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/user/final_7/final_7.srcs/constrs_1/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/user/final_7/final_7.srcs/constrs_1/new/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top demo_2 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef demo_2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file demo_2_utilization_synth.rpt -pb demo_2_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
